apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: node-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-web
  template:
    metadata:
      labels:
        app: node-web
    spec:
      containers:
      - name: node-web
        image: localhost:5000/node-web