version: '3'
services:
 node-web:
   build: .
   volumes:
     - .:/usr/src/app
   container_name: docker-node-tut
   restart: always
   ports:
     - 3000:3000
#  healthcheck:
#     test: curl --fail http://localhost:3000/health || exit 1
    # interval: 60s
    # timeout: 10s
    # retries: 5
    # start_period: 20s